-- I'm sorry
-- The trick here is that the turtle can constantly output a signal, so you can call this once
-- Then you can move in the perscribed sequence, there's better ways to do it, but this was the most straightforward and easy.
redstone.setOutput("right", true)
turtle.turnLeft()
turtle.up()
turtle.up()
turtle.forward()
turtle.forward()
turtle.forward()
turtle.up()
turtle.up()
turtle.up()
turtle.forward()
turtle.forward()
turtle.back()
turtle.down()
turtle.down()
turtle.forward()
turtle.forward()
turtle.up()
turtle.up()
turtle.down()
turtle.down()
turtle.forward()
turtle.forward()
turtle.back()
turtle.up()
turtle.up()
turtle.down()
turtle.down()